### ISSUE TITLE
inconsistent gauge fields: min <= avg <= max doesn't hold

### ISSUE THREAD

**Issue by halber** [vert-x3/vertx-micrometer-metrics#149] opened 2022-07-06 14:56 UTC
### Version

vertx-micrometer-metrics:4.2.7
micrometer-core:1.8.3

### Context

We are using Vertx-micrometer with a Dynatrace. Currently we see many errors of the following type in our logs:

inconsistent gauge fields: min <= avg <= max doesn't hold: min: 13.631488, max: 14.040212, sum: 26.734909, count: 2, avg: 13.367455, tolerance: 0.000001

This message corresponds to the following line sent to Dynatrace:

vertx.pool.usage,instanceid=94c50db5-6927-4517-783a-d379,application=backend_v3-blue,dt.metrics.source=micrometer,pool_type=worker gauge,min=13.631488,max=14.040212,sum=26.734909,count=2 1657115580004

### Do you have a reproducer?

Unfortunately, I have no idea how to provide you with a reproducer.

### Steps to reproduce

Configure vertx to send the metrics to Dynatrace and update to version micrometer-core:1.8.3

**Comment by tsegismont** [comment] 2022-07-08 13:25
This really looks like the problem reported in https://github.com/micrometer-metrics/micrometer/issues/3007

Can you check you actually use 1.8.3 with your Vert.x app?

**Comment by halber** [comment] 2022-07-08 14:37
Yes, I am sure. 
reduced gradle dependency graph:
runtimeClasspath - Runtime classpath of source set 'main'.
+--- ...
|    +--- io.vertx:vertx-micrometer-metrics:4.2.7
|    |    +--- io.micrometer:micrometer-core:1.6.2 -> 1.8.3
...
+--- ...
|    \--- io.micrometer:micrometer-registry-dynatrace:1.8.3
|         +--- io.micrometer:micrometer-core:1.8.3 (*)

**Comment by tsegismont** [comment] 2022-08-10 14:34
Closing for missing details about how to reproduce

**Closed** 2022-08-10 14:34 UTC
Labels: bug, invalid
