### ISSUE TITLE
Endless loop on Gauges#get if tag limit defined and reached.

### ISSUE THREAD

**Issue by wem** [vert-x3/vertx-micrometer-metrics#154] opened 2022-07-08 14:31 UTC
### Version

4.3.2

### Context

If a Tag limit with deny is configured, the function Gauges#get will end up in an endless loop. This because if the limit did deny the tag the gauge instance will be of type NoopGauge, where the ToDoubleFunc never get called. Therefore the for loop will never end.

**Comment by tsegismont** [comment] 2022-07-08 14:45
Thank you @wem , looks like a duplicate of #150

**Closed by tsegismont** 2022-07-08 14:45 UTC
Labels: bug, duplicate
